version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    env_file: 
      - .env 
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ${DB_VOLUME_PATH:-./db}:/app/db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    env_file:
      - .env
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - API_PORT=${API_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    restart: unless-stopped