FROM node:18-alpine

WORKDIR /app

# Install dependencies 
COPY package.json package-lock.json ./
RUN npm install --production

# Copy the rest of the application code
COPY . .
RUN npm run build

ENV PORT=3000
EXPOSE 3000

CMD ["npm", "start"]